import React,{useEffect, useState, createContext} from 'react'
import Head from "next/head";
import { getUserData } from '../../API';
import * as s from './styles'

const UserContext = createContext();

export default function MainLayout({children}) {
  const [userData, setUserData] = useState(null);

  useEffect(() => {
    getUserData(setUserData);
  }, []);
  return (
    <>
    <Head>
      <title>DevHub</title>
      <meta name="description" content="Generated by create next app" />
    </Head>
      <UserContext.Provider value={{ userData, setUserData }}>

    <s.GlobalStyle/>
      <s.Wrapper>
   {children}
      </s.Wrapper>
      </UserContext.Provider>

  </>
  )
}

export { UserContext };
