import React from 'react'
import Head from "next/head";
import * as s from './styles'

export default function MainLayout({children}) {
  return (
    <>
    <Head>
      <title>DevHub</title>
      <meta name="description" content="Generated by create next app" />
    </Head>
    <s.GlobalStyle/>
      <s.Wrapper>
   {children}
      </s.Wrapper>
  </>
  )
}
