import React from "react";
import Head from "next/head";
import styled, { createGlobalStyle } from "styled-components";
import Grid from "../Atoms/Grid";
import MainSection from "../Organisms/MainSection";
// import NavigationBar from "../components/NavigationBar";
import SideSection from "../Organisms/SideSection";

const GlobalStyle = createGlobalStyle`
body {background-color: #0081A7;}
`

const StyledWrapper = styled.div`
  padding-top: 20px;
  width: 80%;
  max-width: 900px;
  margin: auto;
`;

export default function Layout({ children }) {
  return (
    <>
      <Head>
        <title>Mooer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <GlobalStyle/>
        <StyledWrapper>
          <Grid>
            <MainSection>{children}</MainSection>
            <SideSection />
          </Grid>
        </StyledWrapper>
    </>
  );
}
