import React from "react";
import Head from "next/head";
import styled, { createGlobalStyle } from "styled-components";
import MainSection from "../organisms/MainSection";

const GlobalStyle = createGlobalStyle`
body {background-color: #0081A7;}
`

const StyledWrapper = styled.div`
  padding-top: 20px;
  width: 60%;
  max-width: 900px;
  margin: auto;
`;

export default function LayoutUser({ children }) {
  return (
    <>
      <Head>
        <title>Mooer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <GlobalStyle/>
        <StyledWrapper>
            <MainSection>{children}</MainSection>
        </StyledWrapper>
    </>
  );
}
