import React from "react";
import Head from "next/head";
import * as s from './styles'

export default function LayoutCenterDiv({ children }) {
  return (
    <>
    
      <Head>
        <title>Twooter</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <s.BackgroundColor>
        <s.StyledWrapper>
          {children}
        </s.StyledWrapper>
        </s.BackgroundColor>
    </>
  );
}
