import React from "react";
import Head from "next/head";

import styled from "styled-components";

const StyledWrapper = styled.div`
  padding: 20px 0;
  width: 80%;
  margin: auto;
  background-color: white;
`;

const CenteredContainer = styled.div`
width: 50%;
min-width: 300px;
margin: auto;
background-color: lightblue;
padding: 20px;
`

export default function AlternativeLayout({ children }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <StyledWrapper>
      <CenteredContainer>{children}</CenteredContainer>
      </StyledWrapper>
    </>
  );
}
