import React from "react";
import Head from "next/head";
import styled from "styled-components";

const StyledWrapper = styled.div`
  position: relative;
  top: 0;
  left: 0;
  width: 100vw;
  height: 100vh;
`;

const CenteredContainer = styled.div`
  position: absolute;
  left: 50%;
  top: 50%;
  transform: translate(-50%, -50%);
  width: 300px;
  margin: auto;
  background-color: white;
  padding: 20px;
`;

export default function LayoutCenterDiv({ children }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <StyledWrapper>
        <CenteredContainer>{children}</CenteredContainer>
      </StyledWrapper>
    </>
  );
}
