import React from "react";
import Head from "next/head";
import styled from "styled-components";
import Grid from "../components/Grid";
import MainSection from "../components/MainSection";
// import NavigationBar from "../components/NavigationBar";
import SideSection from "../components/SideSection";

const StyledWrapper = styled.div`
  padding-top: 20px;
  width: 80%;
  max-width: 900px;
  margin: auto;
`;

const StyledBody = styled.body`
  background-color: #0081A7;
`

export default function Layout({ children }) {
  return (
    <>
      <Head>
        <title>Mooer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <StyledBody>
        <StyledWrapper>
          <Grid>
            <MainSection>{children}</MainSection>
            <SideSection />
          </Grid>
        </StyledWrapper>
      </StyledBody>
    </>
  );
}
